name:sample caller

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: Prasanna-source31/Test/.github/workflows/080-reusable-workflow-called.yml@main
    with:
      username: Prasanna
    secrets:
      token: ${{ secrets.TOKEN1}}

  
