name: Caller workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'Prasanna'
        required: false
        type: string

jobs:
  gitHub-actions-demo:
    runs-on: ubuntu-latest
    
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run SonarQube workflow
      uses: Prasanna-source31/Reusable/.github/workflows/SonarQube.yml@main
      with:
        username: ${{ github.event.inputs.username }}
