name: 080-resusable-workflow-caller

on:
  push:
    branches: main
  pull_request:
    branches:
     - main
     - develop
  schedule:
    - cron: '30 5 * * 1-5'  # Run every day at 10:00 AM (IST)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: Prasanna-source31/Test/.github/workflows/SonarQube.yml@main
    with:
      username: Prasanna
     
    secrets:
      token: ${{ secrets.TOKEN1 }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}


