name: Caller workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'Prasanna'
        required: false
        type: string

jobs:
  gitHub-actions-demo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SonarQube environment variables
      run: |
        echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> $GITHUB_ENV
        echo "SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}" >> $GITHUB_ENV

    - name: Run SonarQube workflow
      uses: Prasanna-source31/Reusable@main
      with:
        username: ${{ github.event.inputs.username }}
