name: Caller workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'Prasanna'
        required: false
        type: string

jobs:
  gitHub-actions-demo:
    uses: Prasanna-source31/Reusable/.github/workflows/SonarQube.yml@main
  #github-actions-input-demo:
    #uses: amulyakashyap09/resuable-workflows/.github/workflows/manual-trigger-job.yml@main
