name: 080-resusable-workflow-caller

on:
  push:
    branches: main
  pull_request:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: Prasanna-source31/Reusable/.github/workflows/SonarQube.yml@main
    with:
      username: Prasanna
    secrets:
      token: ${{ secrets.TOKEN1 }}


